AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC with public subnet for SFTP Decrypt infrastructure (Cost-optimized, Single AZ)'

Parameters:
  ProjectName:
    Type: String
    Default: 'sftp-decrypt'
    Description: Project name for resource naming and tagging

  VpcCidr:
    Type: String
    Default: '10.0.0.0/16'
    Description: CIDR block for VPC

  PublicSubnet1Cidr:
    Type: String
    Default: '10.0.1.0/24'
    Description: CIDR block for public subnet

Resources:
  # ============================================================================
  # VPC
  # ============================================================================
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'
        - Key: Project
          Value: !Ref ProjectName

  # ============================================================================
  # Internet Gateway
  # ============================================================================
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-igw'
        - Key: Project
          Value: !Ref ProjectName

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # ============================================================================
  # Public Subnet (for Fargate tasks)
  # ============================================================================
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-subnet'
        - Key: Project
          Value: !Ref ProjectName

  # ============================================================================
  # Public Route Table
  # ============================================================================
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-rt'
        - Key: Project
          Value: !Ref ProjectName

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  # ============================================================================
  # VPC Endpoint for S3 (FREE - saves data transfer costs)
  # ============================================================================
  S3VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      RouteTableIds:
        - !Ref PublicRouteTable
      VpcEndpointType: Gateway

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub '${ProjectName}-VpcId'

  VpcCidr:
    Description: VPC CIDR block
    Value: !Ref VpcCidr
    Export:
      Name: !Sub '${ProjectName}-VpcCidr'

  PublicSubnet1Id:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub '${ProjectName}-PublicSubnet1Id'

  PrivateSubnetIds:
    Description: Subnet IDs for Fargate (public subnet, backward compatible export name)
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub '${ProjectName}-PrivateSubnetIds'

  PrivateSubnet1Id:
    Description: Subnet ID for Fargate (public subnet, backward compatible export name)
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub '${ProjectName}-PrivateSubnet1Id'
